before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
    # SDL2
    - sudo apt-get install -y libsdl2{,-mixer,-image,-ttf,-gfx}-dev
    # show sdl version for debug
    - sdl2-config --version

language: go

go:
  - "1.x"
  - "1.8.x"
  - "1.10.x"
  - master

script:
  - go get -v github.com/veandco/go-sdl2/{sdl,mix,img,ttf}
  - cd ../macaw
  - go build
  # this is being used instead of `go test -coverprofile=coverage.txt -covermode=count ./...` 
  # because we get the error in 1.8 'cannot use test profile flag with multiple packages'
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
